### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pppoe** [jwyang/face-alignment#21]
Thanks for the nice work, I am wondering what kind of license it takes?

**Comment by jwyang** [comment]
Hi, it would be MIT license which means you can use it for free of charge in your own project.






At 2015-06-17 04:30:31, "Haoxiang Li" <notifications@github.com> wrote:


Thanks for the nice work, I am wondering what kind of license it takes?

**Comment by pppoe** [comment]
Thanks!
