### ISSUE TITLE
about meanshape

### ISSUE THREAD

**Issue by yyytq** [jwyang/face-alignment#25]
hi. first of all, thanks for your code, it works well . now  i want to do some change on it. 
i want to change the meanshape to my own shape(each pic have their own shape ). but there are always some unknown problems .i'm thinking about if it is  the problem of coordinate. so i want to ask you how your meanshape come from(what is the file used in calc_meanshape.m )? what else should i pay attention to  if i want to do this change?

**Comment by jwyang** [comment]
@yyytq 
Hi, yyytq,

For computing the meanshape, i used afw and the training sets from lfpw, helen. Before computing the mean shape, you may need to first normalize the coordinates first so that all shapes are in the same scale. Otherwise, you will get some wired result
