### ISSUE TITLE
 Undefined function 'train' corresponding to the input parameter of 'double' type.

### ISSUE THREAD

**Issue by mstlimeng** [jwyang/face-alignment#38]
The problem is"Undefined function 'train' corresponding to the input parameter of 'double' type".
The corresponding code is" model = train(deltashapes(:, o), sparse(binaryfeatures), param);"
my environment is 'matlab 2017a'  .  it seems that the function named 'train' is not the same one as the function named 'train' of  the software.which is used to train BP network.

I am looking forward to you replay!
best wishes to you!

**Comment by mstlimeng** [comment]
I have got it! Readme has given the answer :liblinear: http://www.csie.ntu.edu.tw/~cjlin/liblinear/.

**Comment by jwyang** [comment]
great!
